### ISSUE TITLE
Have a warning

### ISSUE THREAD

**Issue by mertozylmz** [homeeondemand/react-native-mapbox-navigation#10]
Hi @rossmartin. Navigation is working. First of all, thank you for your effort.
However, it gives a warning, is there a solution?

`Mapbox warning Falling back to MGLIdeographsRasterizedLocally because  MGLIdeographicFontFamilies are specified. {"filePath": "-[MGLRendererConfiguration glyphsRasterizationOptionsWithLocalFontFamilyName:rasterizationMode:]", "level": "warning", "line": 111, "message": "Falling back to MGLIdeographsRasterizedLocally because  MGLIdeographicFontFamilies are specified."}
`

I also get such an error.
`Mapbox error [event]:General [code]:-1 [message]:Unable to calculate appropriate zoom level for bounds. Vertical or horizontal padding is greater than map's height or width. {"filePath": "virtual bool mbgl::MGLCoreLoggingObserver::onRecord(mbgl::EventSeverity, mbgl::Event, int64_t, const std::string &)", "level": "error", "line": 30, "message": "[event]:General [code]:-1 [message]:Unable to calculate appropriate zoom level for bounds. Vertical or horizontal padding is greater than map's height or width."}`

Finally, is it possible to set the language?

**Comment by rossmartin** [comment]
Those errors appear to be logged by the underlying SDK. I'm not sure what is going on but you could check out issues on the https://github.com/mapbox/mapbox-navigation-ios. There might be an existing one and if not you could open an issue asking about them.

I answered your question about language in #11
