### ISSUE TITLE
Android: Getting the Blank blue screen and when navigate to another screen throwing an error, how can i fixt it

### ISSUE THREAD

**Issue by EdwardLTC** [homeeondemand/react-native-mapbox-navigation#108]
![image](https://user-images.githubusercontent.com/88788257/208449996-7b874d06-28d9-4ef0-b495-0cb7930ca68c.png)

**Comment by EdwardLTC** [comment]
![image](https://user-images.githubusercontent.com/88788257/208450126-89938fff-5d90-4ab5-ab70-1aa994361d8d.png)

**Comment by ahmdsdk** [comment]
@EdwardLTC Did you solve this issue?

**Comment by ahmdsdk** [comment]
I realized this problem has to do with mixing up the latitude and longitude
