### ISSUE TITLE
Android some errors

### ISSUE THREAD

**Issue by mertozylmz** [homeeondemand/react-native-mapbox-navigation#13]
Hello @rossmartin ,
On Android, when I run onCancelNavigation or close the page. It gives errors while unmounting.
I think the problem will be resolved if the OnDestroy code is integrated. Can you fix this?

<img width="1276" alt="Screen Shot 2021-02-18 at 3 22 09 PM" src="https://user-images.githubusercontent.com/16558196/108361546-b01b9c80-7203-11eb-8d83-eece8f78cd6a.png">

**Comment by rossmartin** [comment]
Please see here https://github.com/homeeondemand/react-native-mapbox-navigation/issues/2#issuecomment-744041044 and https://github.com/homeeondemand/react-native-mapbox-navigation/issues/2#issuecomment-763193599

It will only happen in a release build. I'll add that to the README in a future release.

**Comment by mertozylmz** [comment]
@rossmartin Oh, okay man thank you.
