### ISSUE TITLE
Allow hiding of the Navigation Complete banner

### ISSUE THREAD

**Issue by LowBudgetMan** [homeeondemand/react-native-mapbox-navigation#15]
Hello! Is it possible to add an option to hide the banner that shows up on route completion? We're looking to keep displaying the banner that's visible while the map is still navigating. In iOS there's a property to disable it that looks like `showsReportFeedback = false`

<img width="385" alt="Screen Shot 2021-02-22 at 3 54 37 PM" src="https://user-images.githubusercontent.com/37785108/108768975-61814180-7526-11eb-95d2-1be21e8bcc40.png">

**Comment by rossmartin** [comment]
Sorry I've been super busy. When I get some time I will see if this is possible on android also.

**Comment by LowBudgetMan** [comment]
Sure no problem! Good luck with the new place!

**Comment by epavlov** [comment]
Hi @rossmartin ! I have a solution for this on a branch, but for no able to push and make a PR (possibly missing access rights?). How can I contribute?

**Comment by rossmartin** [comment]
@epavlov You can fork the repo here, make the change in your fork, and then PR it.

**Comment by epavlov** [comment]
@rossmartin hey! thanks for the tip, here is a [PR](https://github.com/homeeondemand/react-native-mapbox-navigation/pull/19)

**Comment by rossmartin** [comment]
Implemented for iOS in #19 and android as of https://github.com/homeeondemand/react-native-mapbox-navigation/commit/da30ed2000f0a1945265fe2fbe9c7605cf3e8e43

Released in `1.0.4`.
