### ISSUE TITLE
Destination coordinates mixed 

### ISSUE THREAD

**Issue by zoolle** [homeeondemand/react-native-mapbox-navigation#17]
I was trying to run some tests with different locations and finally I figure out that the latitude and longitude are mixed up

` let originWaypoint = Waypoint(coordinate: CLLocationCoordinate2D(latitude: origin[1] as! CLLocationDegrees, longitude: origin[0] as! CLLocationDegrees))
    let destinationWaypoint = Waypoint(coordinate: CLLocationCoordinate2D(latitude: destination[1] as! CLLocationDegrees, longitude: destination[0] as! CLLocationDegrees))`

Any reason for this?

I should expect `origin=[latitude, longitude] `and `destination=[latitude, longitude]`

**Comment by Kewal89** [comment]
It's probably because MapBox Location parameters (latitude and longitude) are standardized in that way. 
Even [<MapboxGL.Camera />](https://github.com/react-native-mapbox-gl/maps/blob/master/docs/Camera.md) ```centerCoordinate``` props needs ```[lng, lat]``` as value.

**Comment by zoolle** [comment]
That's fine but at least we can put in component, `[lat, lng]` format and then handled from behind in mapbox standard. For example I am using Google maps to get the coordinates of origin and destination and I am passing origin and destination as objects tge way Google maps generates it

**Comment by Kewal89** [comment]
Yeah. Not Sure But You Could Try ```array.reverse()``` or ```[...array].reverse()``` To Make It Work.

**Comment by rossmartin** [comment]
This is an artifact of how this library evolved and also to stay consistent with `@react-native-mapbox-gl/maps`. I do agree that it really should be `[lat, lng]` but I don't plan to change this (for now at least). It is documented here and also with `@react-native-mapbox-gl/maps`. If I do change it to `[lat, lng]` I'll document the breaking change and do a major version bump.
