### ISSUE TITLE
Could not find compatible version for pod "@react-native-mapbox-gl-mapbox-static"

### ISSUE THREAD

**Issue by MaganAnkur** [homeeondemand/react-native-mapbox-navigation#18]
After following all the steps before doing pod install

I am getting below:

[!] CocoaPods could not find compatible versions for pod "@react-native-mapbox-gl-mapbox-static":
  In Podfile:
    react-native-mapbox-gl (from `../node_modules/@react-native-mapbox-gl/maps`) was resolved to 8.1.0, which depends on
      @react-native-mapbox-gl-mapbox-static (~> 5.9.0)

    react-native-mapbox-navigation (from `../node_modules/@homee/react-native-mapbox-navigation`) was resolved to 1.0.2, which depends on
      @react-native-mapbox-gl-mapbox-static (= 6.3.0)

**Comment by rossmartin** [comment]
This can be solved by adding this to the top of your Podfile -

```ruby
$ReactNativeMapboxGLIOSVersion='6.3.0'
```

Note that you might need to delete your `Podfile.lock` file first.

This will allow you to use `@react-native-mapbox-gl/maps` with this library also.

**Comment by MaganAnkur** [comment]
@rossmartin Thanks for your response, above fix worked for me and I am not getting pod compatibility error anymore,

But as soon as I did pod install it started giving me "multiple commands produce" me error.

I fixed this by adding $ReactNativeMapboxGLIOSVersion='6.3.0' below the top line in podfile.

**Now I am getting :**

**Undefined symbol: _swift_getFunctionReplacement**

while building the app.

Your help would be highly appreciated.

Regards

**Comment by MaganAnkur** [comment]
@rossmartin thanks for response, it resolved the issue

**Comment by MaganAnkur** [comment]
@rossmartin It would be highly appreciated if you can help me with below 

After building the app its immediately crashing and seems like below is the error

  assert(false, "This application’s Info.plist file must include “audio” in UIBackgroundModes. This background mode is used for spoken instructions while the application is in the background."

**Comment by MaganAnkur** [comment]
I was able to fix above by inputting UIBackgroundModes as key and value as audio

**Comment by rossmartin** [comment]
Glad you were able to get it figured out. I went ahead and documented `UIBackgroundModes` in the readme.
