### ISSUE TITLE
Xcode - Archiving the project will not show in Organizer

### ISSUE THREAD

**Issue by zoolle** [homeeondemand/react-native-mapbox-navigation#20]
If I build the project and running it on real device or simulator everything is fine. But when I do `Product -> Archive`i t will complete the archive with success but the archive is not in Organizer. If I remove the package from `package.json` and `cd ios && pod update` and try again to archive it eveything is fine. Any reason?

**Comment by rossmartin** [comment]
Are you using `@react-native-mapbox-gl/maps` as well with this library?

It is related to this issue here - https://github.com/react-native-mapbox-gl/maps/issues/1097

This can be fixed by updating `@react-native-mapbox-gl/maps` to `8.1rc5` and adding the following to your Podfile -

```ruby
  pre_install do |installer|
    $RNMBGL.pre_install(installer)
    # other pre install hooks
  end
  post_install do |installer|
    $RNMBGL.post_install(installer)
    # other post install hooks
  end
```

You'll also need this at the top of your Podfile also -

```ruby
$ReactNativeMapboxGLIOSVersion='6.3.0'
```

I have an alternate solution if this does not work for you.

**Comment by zoolle** [comment]
I am not using `@react-native-mapbox-gl/maps`

**Comment by rossmartin** [comment]
This below should solve the problem for you.

Open this file at `ios/Pods/Target Support Files/@react-native-mapbox-gl-mapbox-static/@react-native-mapbox-gl-mapbox-static-copy-dsyms.sh` and comment out lines 85 thru 89 -

```sh
#install_dsym "${PODS_ROOT}/@react-native-mapbox-gl-mapbox-static/dynamic/MapboxMobileEvents.framework.dSYM"
#install_bcsymbolmap "${PODS_ROOT}/@react-native-mapbox-gl-mapbox-static/dynamic/93C58D95-90B9-30C8-8F60-4BDE32FD7E8E.bcsymbolmap"
#install_bcsymbolmap "${PODS_ROOT}/@react-native-mapbox-gl-mapbox-static/dynamic/BB87D8DD-493F-37AA-BD21-2BC609B8311B.bcsymbolmap"
#install_bcsymbolmap "${PODS_ROOT}/@react-native-mapbox-gl-mapbox-static/dynamic/B184533A-B4A2-3D2F-AD72-A6C33D9914F4.bcsymbolmap"
#install_bcsymbolmap "${PODS_ROOT}/@react-native-mapbox-gl-mapbox-static/dynamic/E2FE4B9E-73E5-34BF-B8B9-8FECEBE04D8D.bcsymbolmap"

```

**Comment by zoolle** [comment]
Now this seem to work. Can you please explain how this makes the difference?

**Comment by rossmartin** [comment]
It gets rid of the underpants gnomes.

:~)

Well not really... but if you look at this whole thread here - https://github.com/react-native-mapbox-gl/maps/issues/1097 and specifically this comment https://github.com/react-native-mapbox-gl/maps/issues/1097#issuecomment-770064084 and the one after that.

[This solution from that thread](https://github.com/react-native-mapbox-gl/maps/issues/1097#issuecomment-781647269) is something I'm interested in trying to see if I can get rid of this [pod hack](https://github.com/homeeondemand/react-native-mapbox-navigation/blob/master/react-native-mapbox-navigation.podspec#L22)

**Comment by zoolle** [comment]
Now make sense and thank you

**Comment by udaysagartammina** [comment]
> This below should solve the problem for you.
> 
> Open this file at `ios/Pods/Target Support Files/@react-native-mapbox-gl-mapbox-static/@react-native-mapbox-gl-mapbox-static-copy-dsyms.sh` and comment out lines 85 thru 89 -
> 
> ```shell
> #install_dsym "${PODS_ROOT}/@react-native-mapbox-gl-mapbox-static/dynamic/MapboxMobileEvents.framework.dSYM"
> #install_bcsymbolmap "${PODS_ROOT}/@react-native-mapbox-gl-mapbox-static/dynamic/93C58D95-90B9-30C8-8F60-4BDE32FD7E8E.bcsymbolmap"
> #install_bcsymbolmap "${PODS_ROOT}/@react-native-mapbox-gl-mapbox-static/dynamic/BB87D8DD-493F-37AA-BD21-2BC609B8311B.bcsymbolmap"
> #install_bcsymbolmap "${PODS_ROOT}/@react-native-mapbox-gl-mapbox-static/dynamic/B184533A-B4A2-3D2F-AD72-A6C33D9914F4.bcsymbolmap"
> #install_bcsymbolmap "${PODS_ROOT}/@react-native-mapbox-gl-mapbox-static/dynamic/E2FE4B9E-73E5-34BF-B8B9-8FECEBE04D8D.bcsymbolmap"
> ```

It's working, Thanks.
