### ISSUE TITLE
Unable to install on IOS devices

### ISSUE THREAD

**Issue by AKACC** [homeeondemand/react-native-mapbox-navigation#23]
### Descriptions:
Installed following the instructions. build was successful, but this error popped up.

Xcode: Version 12.4 (12D4e)
iOS: 14.0.1

### Error:
<pre>
Details

Unable to install "test_mapbox"
Domain: com.apple.dt.MobileDeviceErrorDomain
Code: -402653103
--
Could not inspect the application package.
Domain: com.apple.dt.MobileDeviceErrorDomain
Code: -402653103
User Info: {
    DVTRadarComponentKey = 282703;
    MobileDeviceErrorCode = "(0xE8000051)";
    "com.apple.dtdevicekit.stacktrace" = (
	0   DTDeviceKitBase                     0x000000012d0e6c8f DTDKCreateNSErrorFromAMDErrorCode + 220
	1   DTDeviceKitBase                     0x000000012d125241 __90-[DTDKMobileDeviceToken installApplicationBundleAtPath:withOptions:andError:withCallback:]_block_invoke + 155
	2   DVTFoundation                       0x000000010a1fb64b DVTInvokeWithStrongOwnership + 71
	3   DTDeviceKitBase                     0x000000012d124f82 -[DTDKMobileDeviceToken installApplicationBundleAtPath:withOptions:andError:withCallback:] + 1440
	4   IDEiOSSupportCore                   0x000000012cf95a10 __118-[DVTiOSDevice(DVTiPhoneApplicationInstallation) processAppInstallSet:appUninstallSet:installOptions:completionBlock:]_block_invoke.292 + 3513
	5   DVTFoundation                       0x000000010a32a17e __DVT_CALLING_CLIENT_BLOCK__ + 7
	6   DVTFoundation                       0x000000010a32bda0 __DVTDispatchAsync_block_invoke + 1191
	7   libdispatch.dylib                   0x00007fff2023d5dd _dispatch_call_block_and_release + 12
	8   libdispatch.dylib                   0x00007fff2023e7c7 _dispatch_client_callout + 8
	9   libdispatch.dylib                   0x00007fff202445fe _dispatch_lane_serial_drain + 606
	10  libdispatch.dylib                   0x00007fff202450cb _dispatch_lane_invoke + 375
	11  libdispatch.dylib                   0x00007fff2024ec5d _dispatch_workloop_worker_thread + 819
	12  libsystem_pthread.dylib             0x00007fff203e6499 _pthread_wqthread + 314
	13  libsystem_pthread.dylib             0x00007fff203e5467 start_wqthread + 15
);
}
--

System Information

macOS Version 11.2.3 (Build 20D91)
Xcode 12.4 (17801) (Build 12D4e)
Timestamp: 2021-03-10T11:57:51-05:00
</pre>

### Updates:
This error doesn't when I built on simulator. Only happened on real devices.

**Comment by zoolle** [comment]
@AKACC and how is this related to the package?

**Comment by AKACC** [comment]
> @AKACC and how is this related to the package?

I think this package requires MapboxNavigation SDK for IOS, which didn't link properly in my case. I added related frameworks of mapbox to the project and then it works.
