### ISSUE TITLE
Android Build Issue

### ISSUE THREAD

**Issue by MaganAnkur** [homeeondemand/react-native-mapbox-navigation#25]
I am getting below error while building the app on android

Unable to resolve dependency for ':homee_react-native-mapbox-navigation@debug/compileClasspath': Could not resolve com.mapbox.navigation:core:1.3.0.

**Comment by vlkpa** [comment]
Do you have your secret token in gradle.properties file?

**Comment by rossmartin** [comment]
This error can occur if you don't have the repository endpoint declared as shown here with the other instructions - https://github.com/homeeondemand/react-native-mapbox-navigation#android-specific-instructions

**Comment by MaganAnkur** [comment]
> This error can occur if you don't have the repository endpoint declared as shown here with the other instructions - https://github.com/homeeondemand/react-native-mapbox-navigation#android-specific-instructions

Please find my setup below 👍
**gradle.properties**
![Uploading Screen Shot 2021-03-13 at 10.42.58 AM.png…]()

**build.gradle**
![Screen Shot 2021-03-13 at 10 46 54 AM](https://user-images.githubusercontent.com/42070594/111035667-78120e80-83e9-11eb-94b6-261e109f9eb6.png)

**AndroidManifest.xml**
![Screen Shot 2021-03-13 at 10 47 45 AM](https://user-images.githubusercontent.com/42070594/111035726-b3144200-83e9-11eb-89c3-e54450cfc8bc.png)

**Comment by rossmartin** [comment]
Have you tried running a "gradle sync" within Android Studio? Also are you behind a VPN?

**Comment by MaganAnkur** [comment]
It was incorrect secret key.
