### ISSUE TITLE
iOS build -  Having issues building it alongwith @react-native-mapbox-gl/maps package!

### ISSUE THREAD

**Issue by shahraizali** [homeeondemand/react-native-mapbox-navigation#28]
Hi! have you tried building the app which has both of these packages **@react-native-mapbox-gl/maps** and **@homee/react-native-mapbox-navigation** need help with it.

**Comment by bachhuberdesign** [comment]
@shahraizali What issues are you having exactly, and can you provide more info (logs, stack trace, etc.)? We are currently using `@react-native-mapbox-gl/maps` version 8.1.0-rc.9 alongside this library (have not gotten around to upgrading to the stable 8.1.0 for various reasons).

**Comment by rossmartin** [comment]
If you are using a version lower than `8.1.0` for `@react-native-mapbox-gl/maps` you will need to add this entry to the top of your Podfile

```ruby
$ReactNativeMapboxGLIOSVersion='6.3.0'
```

If you are using `8.1.0` or higher please follow these steps here for your Podfile - https://github.com/react-native-mapbox-gl/maps/blob/master/ios/install.md#ios-installation

**Comment by shahraizali** [comment]
I am using `"@react-native-mapbox-gl/maps": "^8.1.0-rc.9"` as well. Initially, it was giving dependency "Mapbox-iOS-SDK" version mismatch. this package requires 6.0 whereas @react-native-mapbox-gl/maps requires 5.9 so I increased it to match 6.0. pods were installed however upon building it's giving this issue.

![rideOS issue](https://user-images.githubusercontent.com/15216270/112590636-f8dafc80-8e24-11eb-85f9-53925f025024.jpeg)
