### ISSUE TITLE
iOS Unimplemented methods

### ISSUE THREAD

**Issue by zoolle** [homeeondemand/react-native-mapbox-navigation#29]
While starting the navigator I get couple of logs for different delegate methods. Is this something that is required?

`[delegation.TopBannerViewController] Unimplemented delegate method in TopBannerViewController: NavigationServiceDelegate.navigationService(_:willArriveAt:after:distance:). This message will only be logged once.`

`[delegation.BottomBannerViewController] Unimplemented delegate method in BottomBannerViewController: NavigationServiceDelegate.navigationService(_:willArriveAt:after:distance:). This message will only be logged once.`

`[delegation.TopBannerViewController] Unimplemented delegate method in TopBannerViewController: NavigationServiceDelegate.navigationService(_:didPassSpokenInstructionPoint:routeProgress:). This message will only be logged once.`

`[delegation.RouteMapViewController] Unimplemented delegate method in RouteMapViewController: NavigationServiceDelegate.navigationService(_:shouldRerouteFrom:). This message will only be logged once.`

`[delegation.TopBannerViewController] Unimplemented delegate method in TopBannerViewController: NavigationServiceDelegate.navigationService(_:shouldRerouteFrom:). This message will only be logged once.`

`[delegation.BottomBannerViewController] Unimplemented delegate method in BottomBannerViewController: NavigationServiceDelegate.navigationService(_:shouldRerouteFrom:). This message will only be logged once.`

`[delegation.MapboxNavigationView] Unimplemented delegate method in MapboxNavigationView: NavigationViewControllerDelegate.navigationViewController(_:shouldRerouteFrom:). This message will only be logged once.`

**Comment by rossmartin** [comment]
These delegate methods on iOS are not required and they are not implemented in the library.
