### ISSUE TITLE
  Could not find Some Dependencies 

### ISSUE THREAD

**Issue by zaidmunir11s** [homeeondemand/react-native-mapbox-navigation#3]
> Could not find com.mapbox.navigation:ui:1.2.1.
> Could not find com.mapbox.navigation:core:1.2.1.

**Comment by rossmartin** [comment]
Were you using a previous version of this wrapper? The latest version published bumped the SDK to `1.2.1` for android.

Try running  "Sync Project with Gradle Files" in android studio and then building. That should fix your issue.

**Comment by rossmartin** [comment]
Stale and have not heard back, closing.
