### ISSUE TITLE
Licensing issue due to upstream mapbox dependency

### ISSUE THREAD

**Issue by karussell** [homeeondemand/react-native-mapbox-navigation#31]
Thanks for providing this interesting project!

From my understanding it should be mentioned in the licensing file that the usage of this project falls under the Mapbox terms. See the [license file](https://github.com/mapbox/mapbox-navigation-android/blob/cac23e6262c451b256aa21a9fa108e8104382ede/LICENSE.md#license-of-dependencies) of the upstream dependency (com.mapbox.navigation:core) version 1.3.0:

> This SDK uses Mapbox Navigator, a private binary, as a dependency. The Mapbox Navigator binary may be used with a Mapbox account and under the Mapbox TOS. If you do not wish to use this binary, make sure you swap out this dependency in libandroid-navigation/build.gradle. 

Please note that it is not trivial to "swap out" this dependency. Additionally Mapbox sends home information from which they say is anonymous (probably to create their traffic data).

And this license becomes effective even if you do not use their services and use some self-hosted map tiles.

And in the [latest version](https://github.com/mapbox/mapbox-navigation-android/blob/main/LICENSE.md) of this upstream dependencies it get's fully closed source:

> Mapbox Navigation for Android version 2.0 (“Mapbox Navigation Android SDK“) or higher must be used according to the Mapbox Terms of Service

I highlight this as I was hoping you found a solution for the problem we faced when we (GraphHopper) forked their navigation SDK before they went closed source a few years ago. This fork is now available under the [MapLibre umrella](https://github.com/maplibre/maplibre-navigation-android) - see a [blog post](https://www.maptiler.com/news/2021/01/mapbox-gl-open-source-fork/) of maptiler - one of the initiator about the reasoning of this org.

**Comment by rossmartin** [comment]
Hey thank you for all of these details. In the next release I'll include this info about the usage of this project falling under Mapbox terms (when this library downloads their SDKs and uses that closed source in conjunction with the open source code here).

I haven't worked on a solution to get around their terms of service but I appreciate you bringing this up and sharing that blog post.
