### ISSUE TITLE
How would .netrc credentials work in production build?

### ISSUE THREAD

**Issue by MaganAnkur** [homeeondemand/react-native-mapbox-navigation#33]

**Comment by bachhuberdesign** [comment]
The same as building locally -- your CI/CD pipeline or the machine you're building on also needs a .netrc file. For our prod builds, we have our MapBox secret key as an environment variable and have a step in the workflow to generate a .netrc file with the proper credentials.

**Comment by MaganAnkur** [comment]
> Hi @MaganAnkur, good question! It is the same as building locally -- your CI/CD pipeline or the machine you're building your prod releases on also needs a .netrc file. For our prod builds, we have our MapBox secret key as an environment variable and have a step at the beginning of our release build workflow that generates the .netrc file with that secret key.
> 
> You could do something like this as a build step:
> 
> ```
> echo "
> machine api.mapbox.com
> login mapbox
> password $YOUR_SECRET_KEY_HERE" >> ~/.netrc
> ```

Thanks @bachhuberdesign for quick response, I will try this.
btw I am using app center for building the app, would it be same in that as well?

**Comment by bachhuberdesign** [comment]
Yep, it should be the same no matter where you are building. I do not have much experience with AppCenter, but you should be able to add a `appcenter-post-clone.sh` file with the above script generating your `.netrc` file. Whatever you have in that script will run after the repo is cloned but before dependencies are added.

https://docs.microsoft.com/en-us/appcenter/build/custom/scripts/#post-clone

**Comment by MaganAnkur** [comment]
> Yep, it should be the same no matter where you are building. I do not have much experience with AppCenter, but you should be able to add a `appcenter-post-clone.sh` file to the root of your repository with the above script generating your `.netrc` file (you would need to add the secret key as a variable on AppCenter). Whatever you have in that script will run after the repo is cloned but before dependencies are installed. Link below:
> 
> https://docs.microsoft.com/en-us/appcenter/build/custom/scripts/#post-clone

Much Appreciated..

**Comment by bachhuberdesign** [comment]
@MaganAnkur Glad to help and have fun building your app 👍

**Comment by Manikandan-saminathan** [comment]
> > Yep, it should be the same no matter where you are building. I do not have much experience with AppCenter, but you should be able to add a `appcenter-post-clone.sh` file to the root of your repository with the above script generating your `.netrc` file (you would need to add the secret key as a variable on AppCenter). Whatever you have in that script will run after the repo is cloned but before dependencies are installed. Link below:
> > https://docs.microsoft.com/en-us/appcenter/build/custom/scripts/#post-clone
> 
> Much Appreciated.

Is there any Update on this issue I tried this method but it is not working for me

**Comment by XFAISAL** [comment]
even me
