### ISSUE TITLE
Error inflating Layoput/com.mpbox.navigation.ui.summary.SummaryBottomSheet

### ISSUE THREAD

**Issue by mirzahayat** [homeeondemand/react-native-mapbox-navigation#59]
After integration the @homee/react-native-mapbox-navigation.  version 1.1.0 with all configuration  , i'm facing this issues com.mpbox.navigation.ui.summary.SummaryBottomSheet 
SO please help me how i can fix it,

**Comment by mirzahayat** [comment]
i have resolve this error 2 to 3 steps,
1: check that your key is correct public and secret,
2: try to use gradle version gradle-6.7-all.zip

sync the project y Android Studio and run 

hope so it will help you.

**Comment by mohammedelnady** [comment]
did you resolve that issue ?
