### ISSUE TITLE
Is this still maintained?

### ISSUE THREAD

**Issue by zoolle** [homeeondemand/react-native-mapbox-navigation#64]
I can see that there is MapBox Navigation SDK 2.0 but I haven't seen an update of this project for couple of months is someone still working on it?

**Comment by JorgeQuevedoC** [comment]
I think it is a great question and is important to know for some projects that are in progress

**Comment by joe307bad** [comment]
This project is still used in production, just not in active development. Pull requests are welcome. We are trying to dedicate time to the active development of this library and will hopefully have some progress in the coming months.

**Comment by haizenburg** [comment]
Hi @joe307bad  who do i talk to if i wish to contribute?

**Comment by joe307bad** [comment]
Hey @haizenburg, thanks for reaching out. I am the point of contact for contributing to this repo. Please feel free to open a PR and I'd be happy to review and merge ☺️

**Comment by joe307bad** [comment]
Hey @JorgeQuevedoC, thats a good question. I would say that any PR would probably benefit from also adding an example app to this project? That seems like the best way to test any changes. If someone were to put up a pull request I would be happy to make some time to also a minimal example project.

**Comment by JorgeQuevedoC** [comment]
Hi @joe307bad I have done some changes but I don't know how to test them on my project before I create the PR. Any suggestion?

**Comment by joe307bad** [comment]
Hey @JorgeQuevedoC, thanks for taking the time to work on this, I really appreciate it.

I would say the best way to test is to add an `/example` directory to the root of this repo and use `npx react-native init` to add an example application. Once the example app is created, we can create a basic implementation of `react-native-mapbox-navigation` within this repo. I have seen other packages do this and I think its probably the best practice, what do you think think?

Also, I wouldn't worry about testing your changes before posting the PR. Feel free to post the PR without an example app and I would be happy to work with you to figure out the best way to test.

**Comment by JorgeQuevedoC** [comment]
@joe307bad would you mind having a call to ask you a couple of thing about it?

**Comment by joe307bad** [comment]
Hey @JorgeQuevedoC, I would be more than happy to have a call but lets exhaust some options before we try to coordinate a phone call. Could you post your PR and allow me to take a look? Do you have a specific error you may be running into?

**Comment by JorgeQuevedoC** [comment]
@joe307bad There are no errors because I don't know how to run the changes locally to see if it works

**Comment by joe307bad** [comment]
Thanks @JorgeQuevedoC, feel free to post a PR and we can communicate about any new code within that PR. I would be happy to coordinate a call when I can look at some code and formulate a strategy for testing the changes you would like to make 😄

**Comment by JorgeQuevedoC** [comment]
@joe307bad 
![image](https://user-images.githubusercontent.com/19591200/150030394-5378926d-124f-4f2f-bd73-de8086573ce2.png)
Can you give me access ?
