### ISSUE TITLE
Add onArrive prop

### ISSUE THREAD

**Issue by rossmartin** [homeeondemand/react-native-mapbox-navigation#7]
TODO: Add a prop called `onArrive` that takes a function to get called when the "End Navigation" button is pressed (or  when navigation finishes transparently).

**Comment by mertozylmz** [comment]
When will you add this function? :)
Also you did a very good job.

**Comment by rossmartin** [comment]
Hey thank you I had some time last night and got this functionality added in. I merged the branch into master just now and tagged/released `0.2.2` to npm.
