### ISSUE TITLE
Issues with installation android

### ISSUE THREAD

**Issue by jamesvovos** [homeeondemand/react-native-mapbox-navigation#84]
Looking forward to using this library, however I keep getting errors whenever I'm trying to install it for Android - any solutions? I see it's quite common in the issues threads.

![issue1](https://user-images.githubusercontent.com/79495095/163760898-48e25b84-7771-4ae5-bce2-732bdc606861.PNG)
![issue2](https://user-images.githubusercontent.com/79495095/163760902-890ab56e-91a5-4537-95a4-1e5f66bb5f1e.PNG)

**Comment by sarafhbk** [comment]
Hey @jamesvovos  If you're encountering issues with the original version, I'd like to invite you to try my fork of React Native Mapbox Navigation. I've made some enhancements and fixes that might address your concerns. You can easily install it using npm with the following command:

npm install https://github.com/sarafhbk/react-native-mapbox-navigation

I'm eager to hear your feedback and improve it further, so please don't hesitate to share your thoughts and experiences!

**Comment by jhanzaibkhadim199** [comment]
Hey @sarafhbk  I am using your forked version but on android its not starting navigation guide only opening map can you suggest me anything or help me resolve this issue ? I have been on this for weeks now. 
![IMG_7881](https://github.com/homeeondemand/react-native-mapbox-navigation/assets/103829403/449fe734-6e06-4bbc-a823-61ad94ed8ffb)
